//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileTopUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string PaymentType { get; set; }
        public string PaymentRef { get; set; }
        public string Currency { get; set; }
        public decimal ExchangeRate { get; set; }
        public string Brand { get; set; }
        public decimal TotalDenomination { get; set; }
        public decimal SellingPrice { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    }
}
