//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileTopUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int ID { get; set; }
        public decimal Amount { get; set; }
        public string Number { get; set; }
        public byte[] Image { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TransactionID { get; set; }
    }
}
